# Generated by Django 3.1.2 on 2021-03-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='new_work',
        ),
        migrations.AddField(
            model_name='work',
            name='new_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
