# Generated by Django 3.1.2 on 2021-03-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210304_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='new_title',
            new_name='title',
        ),
    ]
